# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  bundle:
    docker:
      - image: circleci/node:9.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install packages
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run:
          name: Bundle project
          command: npm run bundle

      - persist_to_workspace:
          root: .
          paths:
            - dist
  build:
    docker:
      - image: docker:18.02.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run:
          name: Build and Deploy image to hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/buybinds:$CIRCLE_TAG .
            docker push $DOCKER_USER/buybinds:$CIRCLE_TAG

workflows:
  version: 2
  bundle_and_build:
    jobs:
      - bundle:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build:
          requires:
            - bundle
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/