name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/buybinds:${{ github.run_number }} .
    - name: Push
      run: docker push ${{ secrets.DOCKER_USER }}/buybinds:${{ github.run_number }}