name: Linter

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@master
        with:
          files: src/
